# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  - push
  - pull_request

jobs:
  install-and-build:
    runs-on: ubuntu-latest
    env:
      DATABASE_CLIENT: sqlite
      DATABASE_URL: db/test.db

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
  
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          
      - run: pnpm install --frozen-lockfile
      - run: pnpm test
      - run: pnpm build --if-present
